### PR TITLE
first pull request, tryout

### PR DESCRIPTION
**Pull request by brugi94**
pull request tryout.
requesting to add ringPhone and displayToast methods and the Alarm_Not_Found_Exception class

### CODE REVIEW

**Comment by massimo** [comment]
warning, wrong github user.

Massimo

**Comment by brugi94** [comment]
I haven't selected any github user, i've jsut sent a pull request from my branch to master

**Comment by massimo** [comment]
Weird.

**Comment by brugi94** [comment]
closing this one, new try incoming

**Pull request closed without merging**
